#!/bin/bash

while [[ $# == 0 ]]
do
    echo ""
    echo "  Usage: keef [command]"
    echo ""
    echo "      data_train    begins the training data pipeline"
    echo "      data_test     begins the testing data pipeline"
    echo "      test          Runs tests"
    echo ""
    break
done

# Parse argument
while [[ $# == 1 ]]
do
    arg="$1"
    case $arg in
        data_train)
       		echo "Running train pipeline"
        	PIPELINE=train python pipeline/tasks.py
                shift
                ;;
        data_test)
                echo "Running test pipeline"
                PIPELINE=test python pipeline/tasks.py
                shift
                ;;
	test)
	    nosetests --with-specplugin
	    shift
	    ;;
    	*)
            echo "" 
            echo "  Argument '$arg' not recognized"
            ./keef
            shift
            ;;
    esac
    break
done
