#!/bin/bash

while [[ $# == 0 ]]
do
    echo ""
    echo "  Usage: keef [command]"
    echo ""
    echo "      data train    begins the training data pipeline"
    echo "      data test     begins the testing data pipeline"
    echo "      test          Runs tests"
    echo ""
    break
done

# Parse argument
while [[ $# -le 2 ]]
do
    arg="$1"
    case $arg in
        data)
            arg2="$2"
            case $arg2 in
                test)
                    echo "Running test pipeline"
                    PIPELINE=test python pipeline/tasks.py
                    shift
                    ;;
                train)
                    echo "Running train pipeline"
                    PIPELINE=train python pipeline/tasks.py
                    shift
                    ;;
            esac 
            shift
            ;;
	test)
	    nosetests --with-specplugin
	    shift
	    ;;
    	*)
            echo "" 
            echo "  Argument '$arg' not recognized"
            ./keef
            shift
            ;;
    esac
    break
done
